### ISSUE TITLE
不能添加项目成员

### ISSUE THREAD

**Issue by thimper** [twang2218/gitlab-ce-zh#37]
项目设置不添加成员，选择开发人员，不搜人员，进行添加：

chrome console 有如下错误：

gl_emoji.js:4 Uncaught TypeError: w(...) is not a function
    at Object../behaviors/index.js (gl_emoji.js:4)
    at r (bootstrap 4ef9fae7bd6e77b9818c:54)
    at Object.<anonymous> (main.b059a010247315b51313.bundle.js:24627)
    at Object../main.js (main.b059a010247315b51313.bundle.js:25134)
    at r (bootstrap 4ef9fae7bd6e77b9818c:54)
    at window.webpackJsonp (bootstrap 4ef9fae7bd6e77b9818c:25)
    at main.b059a010247315b51313.bundle.js:1

**Comment by kawhii** [comment]
是的，9.5.2也不行，需要如何解决 @twang2218

**Comment by VAllens** [comment]
@kawhii +1，我的也是。升级到`10.0.3`后，发现太多明显的BUG，实在不行回退到`9.5.2`。
但回退后又出现新的问题：已经登录的人正常使用，而尝试登录的人，死活登录不了，并且如果已经登录过的人退出登录后，想要再次登录也会有这个问题。
我这边是LDAP认证登录方式，总是提示`Could not authenticate you from Ldapmain because "Undefined method `external email=' for #<user id:2 @myname> did you mean? external=".`
但我使用gitlab-rake gitlab:ldap:check命令检查LDAP，却又是正常的，奇葩。

**Comment by VAllens** [comment]
自己用docker build构建10.1.0版本，解决所有问题。

**Comment by twang2218** [comment]
问题最初是由于 yarn 1.x 不支持早期版本生成的 `yarn.lock`，在 10.0 分支开始的时候，使用的是临时的解决办法，删除了 `yarn.lock` 使得构建可以通过，但是随后发现，这样做引发了 JS 依赖库的版本混乱，从而导致很多库间调用出现问题，纯粹依赖 `package.json` 很是问题。

非常抱歉之前一直没能抽出时间修正这个问题，这几天有时间修复了一下。这次我不再删除 `yarn.lock`，而是 `apt` 安装的时候指定 YARN 版本为 `0.27`，这样就会支持 `1.0` 之前版本生成的 `yarn.lock` 了。在 `10.2` 之后，会有新的 `yarn.lock`，应该就不需要指定版本了。现在正在构建新的版本，等构建好后可以测试一下。

**Comment by VAllens** [comment]
mark

**Comment by twang2218** [comment]
长时间未回复，关闭 issue。如果还有问题可以重新开启。
